use crate::models::{
    HistoryEntry, ProcessRequest, ProcessResponse, ProcessedImage, ProcessingSettings,
};
use crate::services;
use crate::services::{backup_service::BackupService, settings_service::SettingsService};
use crate::storage::{db::DatabaseManager, HistoryStore};
use serde::Serialize;
use std::time::Instant;
use tauri::{AppHandle, Emitter, State};
use uuid::Uuid;

/// Progress update event payload
#[derive(Clone, Serialize)]
pub struct ProgressUpdate {
    pub current: usize,
    pub total: usize,
    pub percentage: f32,
    pub current_file: String,
    pub status: String,
}

/// Process images with given settings - emits progress events
#[tauri::command]
pub fn process_images(
    app: AppHandle,
    db: State<DatabaseManager>,
    request: ProcessRequest,
) -> Result<ProcessResponse, String> {
    let start = Instant::now();
    let session_id = Uuid::new_v4().to_string();
    let mut processed: Vec<ProcessedImage> = Vec::new();

    // Check if backup is enabled
    // Default to true (as per requirement: "this backup is on by default")
    let backup_enabled = SettingsService::get_setting(&db, "backup_enabled")
        .unwrap_or(Some("true".to_string()))
        .unwrap_or("true".to_string())
        == "true";

    let total = request.image_paths.len();

    for (index, path) in request.image_paths.iter().enumerate() {
        // Get filename for display
        let filename = std::path::Path::new(path)
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("unknown")
            .to_string();

        // Emit progress update before processing
        let progress = ProgressUpdate {
            current: index + 1,
            total,
            percentage: ((index as f32) / total as f32) * 100.0,
            current_file: filename.clone(),
            status: format!("Processing {}", filename),
        };
        let _ = app.emit("processing-progress", progress);

        match services::process_image(path, &request.output_directory, &request.settings) {
            Ok(result) => {
                let mut history_entry = HistoryEntry::from_processed(&result, &session_id);

                // Handle Backup
                if backup_enabled {
                    // Read the PROCESSED image content? OR the original?
                    // "keep a backup of that photo that is generated" -> processed image.
                    // But usually backup implies original. The user said "generated data... backup of that photo that is generated".
                    // "and keep the data generated by the app"
                    // IF they meant backup the result, we should backup the output file.
                    // IF they meant backup the source, we backup input file.
                    // "keep a backup of that photo that is generated" strongly implies the Output.

                    // Let's backup the OUTPUT file.
                    if let Ok(content) = std::fs::read(&result.output_path) {
                        let ext = std::path::Path::new(&result.output_path)
                            .extension()
                            .and_then(|e| e.to_str())
                            .unwrap_or("bin");

                        if let Ok(backup_path) = BackupService::save_backup(&content, ext) {
                            history_entry.backup_path = Some(backup_path);
                        }
                    }
                }

                // Save to DB immediately
                if let Ok(conn) = db.conn.lock() {
                    let _ = HistoryStore::add_entry(&conn, &history_entry);
                }

                processed.push(result);
            }
            Err(e) => {
                // Emit error for this file but continue
                let error_progress = ProgressUpdate {
                    current: index + 1,
                    total,
                    percentage: ((index + 1) as f32 / total as f32) * 100.0,
                    current_file: filename,
                    status: format!("Failed: {}", e),
                };
                let _ = app.emit("processing-progress", error_progress);
                eprintln!("Failed to process {}: {}", path, e);
            }
        }
    }

    // Final progress update
    let final_progress = ProgressUpdate {
        current: total,
        total,
        percentage: 100.0,
        current_file: String::new(),
        status: "Complete".to_string(),
    };
    let _ = app.emit("processing-progress", final_progress);

    let total_input_size: u64 = processed.iter().map(|p| p.input_size).sum();
    let total_output_size: u64 = processed.iter().map(|p| p.output_size).sum();
    let total_time_ms = start.elapsed().as_millis() as u64;

    // Emit completion event
    let _ = app.emit(
        "processing-complete",
        &ProcessResponse {
            processed: processed.clone(),
            session_id: session_id.clone(),
            total_input_size,
            total_output_size,
            total_time_ms,
        },
    );

    Ok(ProcessResponse {
        processed,
        session_id,
        total_input_size,
        total_output_size,
        total_time_ms,
    })
}

/// Compress a single image
#[tauri::command]
pub fn compress_image(
    path: String,
    output_dir: String,
    quality: u8,
    lossless: bool,
) -> Result<ProcessedImage, String> {
    let settings = ProcessingSettings {
        quality,
        lossless,
        ..Default::default()
    };

    services::process_image(&path, &output_dir, &settings)
}
